FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

MAINTAINER Sakakibara Akiyuki <moritarizumu@gmail.com>

ARG OPENCV_VERSION="3.4.1"
ARG PYTHON_VERSION="3.5"

# set cudnn versio
RUN apt-get update \
&&  apt-get install -y --allow-downgrades --no-install-recommends \
                    libcudnn7=7.0.5.15-1+cuda9.0 \
		    libcudnn7-dev=7.0.5.15-1+cuda9.0 \
&&  rm -rf /var/lib/apt/lists/* \
&&  apt-get update

### package needed
RUN apt-get update && apt-get install -y git apt-file pkg-config wget unzip \
&&  apt-file update \
&&  apt-file search add-apt-repository \
&&  apt-get install -y software-properties-common \
                       python-software-properties \
                       apt-transport-https \
### python install
&&  apt-get install -y python3-dev \
                       python3-pip \
                       python3-setuptools \
                       libatlas-dev \
&&  pip3 install --upgrade pip \
&&  pip3 install numpy pylint
### for build opencv 
RUN apt-get update \
&&  apt-get install -y cmake build-essential libgtk2.0-dev\
                       libavcodec-dev libavformat-dev libswscale-dev \
                       libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
                       libjasper-dev libdc1394-22-dev libeigen3-dev libtbb-dev \
                       libopenblas-dev liblapack-dev ffmpeg\
		       vtk6 tcl-vtk6 python-vtk6 libvtk6-dev
# cal env
## install opencv without CUDA
WORKDIR /root

RUN wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip \
&&  unzip -qq ${OPENCV_VERSION}.zip \
&&  rm ${OPENCV_VERSION}.zip \
&&  wget https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip \
&&  unzip -qq ${OPENCV_VERSION}.zip \
&&  rm ${OPENCV_VERSION}.zip \
&&  mkdir opencv-${OPENCV_VERSION}/cmake_binary \
&&  cd opencv-${OPENCV_VERSION}/cmake_binary \
&&  cmake \
      -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
      -D BUILD_EXAMPLES=ON \
      -D BUILD_NEW_PYTHON_SUPPORT=ON \
      -D BUILD_opencv_python3=ON \
      -D BUILD_opencv_python2=OFF \
      -D ENABLE_FAST_MATH=1 \
      -D WITH_V4L=ON \
      -D WITH_FFMPEG=ON \
      -D WITH_TBB=ON \
      -D WITH_OPENCL=ON \
      -D WITH_MATLAB=OFF \
      -D WITH_JAVA=OFF \
      -D WITH_CUDA=OFF \
      -D INSTALL_PYTHON_EXAMPLES=OFF \
      -D PYTHON3_EXECUTABLE=/usr/bin/python3 \
      -D PYTHON3_INCLUDE_DIR=/usr/include/python${PYTHON_VERSION}m \
      -D PYTHON3_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython${PYTHON_VERSION}m \
      -D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/local/lib/python3.5/dist-packages/numpy/core/include \
      -D PYTHON3_PACKAGES_PATH=/usr/local/lib/python3.5/dist-packages \
      -D PY_PIP=/usr/local/lib/python3.5/dist-packages/pip \
      .. \
&&  make -j$(nproc) \
&&  make install \
&&  cp lib/python3/cv2.* /usr/local/lib/python${PYTHON_VERSION}/dist-packages/ \
&&  cd /root \
&&  rm -rf opencv*
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

## install boost
RUN wget -O - 'https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz' | tar zxvf - \
&&  cd boost* \
&&  ./bootstrap.sh --with-libraries=python --with-python=python3 \
&&  ./b2 install -j$(nproc) \
&&  cd .. \
&&  rm -r boost*

## install dlib
ARG DLIB_VERSION="v19.6"
RUN wget https://github.com/davisking/dlib/archive/${DLIB_VERSION}.zip \
&&  unzip ${DLIB_VERSION}.zip \
&&  rm ${DLIB_VERSION}.zip \
&&  cd dlib* \
&&  python3 setup.py install \
&&  cd .. \
&&  rm -r dlib*

## tensorflow and jupyter notebook lab
WORKDIR /root
RUN pip3 install tensorflow-gpu \
&&  pip3 install jupyter \
&&  pip3 install jupyterlab \
&&  jupyter serverextension enable --py jupyterlab --sys-prefix \
&&  python3 -m IPython kernelspec install-self \
## other python packages
&&  pip3 install scikit-learn \
                 pandas \
                 xlrd\
                 pypdf2 \
                 h5py \
                 keras \
                 PyWavelets \
                 pydicom \

## set jupyter notebook
&&  jupyter notebook --generate-config
ADD jupyter-init-setting-python3.py /workspace/
ADD run_jupyter.sh /workspace/
RUN chmod +x /workspace/run_jupyter.sh
# ## set matplotlib backend
# RUN mkdir ~/.config/matplotlib \
# &&  echo 'backend : Qt4Agg' >> $HOME/.config/matplotlib/matplotlibrc

# webcolors
ARG WEBCOLORS_VERSION="master"
RUN wget https://github.com/ubernostrum/webcolors/archive/${WEBCOLORS_VERSION}.zip \
&&  unzip ${WEBCOLORS_VERSION}.zip \
&&  rm ${WEBCOLORS_VERSION}.zip \
&&  cd webcolors* \
&&  python3 setup.py install \
&&  cd .. \
&&  rm -rf webcolors* 


# tools env
## make sudo user
# crypt(passwd, salt)
ARG USER_NAME='hoge'
ARG UID='1000'
ARG PASSWD='password'
RUN apt-get update \
&&  apt-get install -y sudo \
&&  echo ${USER_NAME}' ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
&&  useradd -u ${UID} -G sudo -p `perl -e "print(crypt('${PASSWD}', 'wN'));"` ${USER_NAME} \
&&  mkdir /home/${USER_NAME} \
&&  chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}

USER ${USER_NAME}
WORKDIR /home/${USER_NAME}

# install fish shell and arounds
## install powerline fonts
ARG POWERLINEFONT_VERSION="master"
RUN wget https://github.com/powerline/fonts/archive/${POWERLINEFONT_VERSION}.zip \
&&  unzip ${POWERLINEFONT_VERSION}.zip \
&&  rm ${POWERLINEFONT_VERSION}.zip \
&&  cd fonts*  \
&&  ./install.sh  \
&&  cd .. \
&&  rm -rf fonts* \
&&  fc-cache -vf ~/.local/share/fonts/
ENV LC_CTYPE='ja_JP.UTF-8'

### install fish
RUN mkdir ~/.config \
&&  mkdir ~/.config/fish
ADD config.fish /home/${USER_NAME}/.config/fish/
ADD fish_config.sh /home/${USER_NAME}/
RUN sudo chmod +x fish_config.sh \
&&  sudo add-apt-repository ppa:fish-shell/release-2 \
&&  sudo apt-get update \
&&  sudo apt-get install -y fish \
&&  sudo apt-get -y install language-pack-ja-base \
#### install fisherman
&&  curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher \
&&  sudo chmod +x fish_config.sh \
&&  ./fish_config.sh \
&&  rm fish_config.sh \
#### install peco
&&  wget -O - 'https://github.com/peco/peco/releases/download/v0.5.1/peco_linux_amd64.tar.gz' | tar zxvf - \
&&  sudo mv peco_linux_amd64/peco /usr/local/bin/ \
&&  rm -rf peco_linux_amd64 \
#### set fish shell as a default
&&  sudo chsh -s /usr/bin/fish \
&&  sudo chsh -s /usr/bin/fish ${USER_NAME}

# install editor
RUN sudo apt-get update \
&&  sudo apt-get install -y vim \
## install rsub for sublime text via ssh
&&  sudo wget -O /usr/local/bin/rsub https://raw.github.com/aurora/rmate/master/rmate \
&&  sudo chmod +x /usr/local/bin/rsub 

# install ssh
WORKDIR /workspace
RUN sudo chown -R $USER_NAME:$USER_NAME /workspace
